<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name'          => 'Jamu Beras Kencur Premium',
                'slug'          => 'jamu-beras-kencur-premium',
                'description'   => 'Jamu tradisional khas Jawa yang terbuat dari beras dan kencur pilihan. Menyegarkan dan menyehatkan tubuh secara alami.',
                'usage'         => "1. Kocok botol sebelum diminum\n2. Minum 1-2 sendok makan 2× sehari\n3. Sajikan sebelum makan atau sesudah makan\n4. Simpan di tempat sejuk dan kering",
                'benefits'      => "• Meningkatkan nafsu makan\n• Menghilangkan pegal-pegal\n• Menyegarkan badan\n• Meningkatkan stamina dan vitalitas",
                'composition'   => "Beras (Oryza sativa), Kencur (Kaempferia galanga), Jahe (Zingiber officinale), Gula Aren, Air",
                'price'         => 35000,
                'discount_price'=> 29000,
                'stock'         => 150,
                'is_featured'   => true,
                'is_bestseller' => true,
                'rating'        => 4.8,
                'rating_count'  => 247,
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'Ekstrak Temulawak & Kunyit',
                'slug'          => 'ekstrak-temulawak-kunyit',
                'description'   => 'Formula herbal kuat dari temulawak dan kunyit yang telah terbukti secara klinis mendukung kesehatan pencernaan dan liver.',
                'usage'         => "1. Minum 2 kapsul sebelum makan\n2. Konsumsi rutin 2× sehari\n3. Minum dengan air putih yang cukup\n4. Dianjurkan untuk orang dewasa di atas 17 tahun",
                'benefits'      => "• Menjaga kesehatan liver/hati\n• Melancarkan pencernaan\n• Anti-inflamasi alami\n• Meningkatkan sistem imun",
                'composition'   => "Temulawak (Curcuma xanthorrhiza) 250mg, Kunyit (Curcuma longa) 200mg, Ekstrak Lada Hitam",
                'price'         => 85000,
                'discount_price'=> null,
                'stock'         => 80,
                'is_featured'   => true,
                'is_bestseller' => false,
                'rating'        => 4.7,
                'rating_count'  => 183,
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'Kapsul Sambiloto Diabetes Care',
                'slug'          => 'kapsul-sambiloto-diabetes-care',
                'description'   => 'Herbal pilihan untuk membantu menjaga kadar gula darah tetap normal. Mengandung sambiloto berkualitas tinggi.',
                'usage'         => "1. Konsumsi 3 kapsul per hari\n2. Diminum sesudah makan\n3. Minum air putih minimal 8 gelas per hari\n4. Jaga pola makan sehat",
                'benefits'      => "• Membantu menstabilkan gula darah\n• Mendukung fungsi pankreas\n• Anti-diabetes alami\n• Tidak ada efek samping berbahaya",
                'composition'   => "Sambiloto (Andrographis paniculata) 400mg, Pare (Momordica charantia) 200mg, Brotowali",
                'price'         => 120000,
                'discount_price'=> 99000,
                'stock'         => 60,
                'is_featured'   => true,
                'is_bestseller' => true,
                'rating'        => 4.9,
                'rating_count'  => 312,
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'Herbal Nyeri Sendi Plus',
                'slug'          => 'herbal-nyeri-sendi-plus',
                'description'   => 'Formulasi herbal eksklusif untuk mengatasi nyeri sendi, asam urat, dan rematik. Cocok untuk orang dewasa dan lansia.',
                'usage'         => "1. Minum 2 kapsul pagi dan sore\n2. Jangan melebihi dosis yang dianjurkan\n3. Hindari makanan tinggi purin\n4. Olahraga ringan secara teratur",
                'benefits'      => "• Meredakan nyeri sendi\n• Mengurangi peradangan\n• Mengatasi asam urat\n• Memperbaiki mobilitas sendi",
                'composition'   => "Jahe Merah (Zingiber officinale var. rubrum) 300mg, Temu Kunci, Lada Hitam, Minyak Zaitun",
                'price'         => 95000,
                'discount_price'=> 79000,
                'stock'         => 90,
                'is_featured'   => false,
                'is_bestseller' => true,
                'rating'        => 4.6,
                'rating_count'  => 198,
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'Teh Herbal Kidney Cleanse',
                'slug'          => 'teh-herbal-kidney-cleanse',
                'description'   => 'Teh herbal alami untuk membantu membersihkan dan menjaga fungsi ginjal. Rasa yang enak dan menyegarkan.',
                'usage'         => "1. Seduh 1 sachet dengan 200ml air panas\n2. Diamkan 5-7 menit sebelum diminum\n3. Minum 2× sehari pagi dan malam\n4. Tambahkan madu untuk rasa manis alami",
                'benefits'      => "• Membantu detoksifikasi ginjal\n• Melancarkan buang air kecil\n• Mencegah batu ginjal\n• Meredakan infeksi saluran kemih",
                'composition'   => "Daun Kumis Kucing (Orthosiphon aristatus), Daun Tempuyung, Meniran (Phyllanthus niruri), Akar Alang-alang",
                'price'         => 55000,
                'discount_price'=> null,
                'stock'         => 200,
                'is_featured'   => true,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 156,
                'categories'    => ['ginjal'],
            ],
            [
                'name'          => 'Minyak Cengkeh & Kayu Putih',
                'slug'          => 'minyak-cengkeh-kayu-putih',
                'description'   => 'Minyak oles herbal multifungsi dari cengkeh dan kayu putih premium untuk masuk angin, pegal, dan nyeri otot.',
                'usage'         => "1. Oleskan pada bagian yang sakit\n2. Pijat perlahan selama 2-3 menit\n3. Gunakan 3-4× sehari sesuai kebutuhan\n4. Hindari kontak dengan mata",
                'benefits'      => "• Menghangatkan tubuh\n• Meredakan masuk angin\n• Mengurangi nyeri otot\n• Aromaterapi alami",
                'composition'   => "Minyak Cengkeh (Syzygium aromaticum), Minyak Kayu Putih (Melaleuca cajuputi), Minyak Zaitun Murni",
                'price'         => 45000,
                'discount_price'=> 38000,
                'stock'         => 175,
                'is_featured'   => false,
                'is_bestseller' => true,
                'rating'        => 4.7,
                'rating_count'  => 289,
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'Propolis Plus Madu Hutan',
                'slug'          => 'propolis-plus-madu-hutan',
                'description'   => 'Kombinasi propolis alami dan madu hutan untuk meningkatkan imunitas tubuh secara menyeluruh.',
                'usage'         => "1. Teteskan 10-15 tetes ke dalam air\n2. Minum 2× sehari pagi dan malam\n3. Bisa langsung diteteskan ke bawah lidah\n4. Untuk anak: 5-8 tetes",
                'benefits'      => "• Meningkatkan daya tahan tubuh\n• Antibakteri dan antiviral alami\n• Mempercepat pemulihan\n• Menjaga kesehatan mulut",
                'composition'   => "Propolis Alami 30%, Madu Hutan (Apis dorsata) 60%, Aquades",
                'price'         => 145000,
                'discount_price'=> 125000,
                'stock'         => 45,
                'is_featured'   => true,
                'is_bestseller' => true,
                'rating'        => 4.9,
                'rating_count'  => 401,
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'Serbuk Jahe Merah Instan',
                'slug'          => 'serbuk-jahe-merah-instan',
                'description'   => 'Minuman serbuk jahe merah premium yang praktis dan lezat. Cocok untuk menghangatkan tubuh di pagi dan malam hari.',
                'usage'         => "1. Larutkan 1 sachet dalam 200ml air panas\n2. Aduk hingga larut sempurna\n3. Bisa ditambahkan susu atau madu\n4. Nikmati 1-2 kali sehari",
                'benefits'      => "• Menghangatkan tubuh\n• Meningkatkan stamina\n• Anti mual dan perut kembung\n• Menjaga daya tahan tubuh",
                'composition'   => "Jahe Merah (Zingiber officinale var. rubrum) 40%, Gula Kelapa, Kayu Manis, Sereh",
                'price'         => 65000,
                'discount_price'=> null,
                'stock'         => 130,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.4,
                'rating_count'  => 97,
                'categories'    => ['stamina', 'imunitas'],
            ],
            [
                'name'          => 'Kapsul Pegagan Brain Booster',
                'slug'          => 'kapsul-pegagan-brain-booster',
                'description'   => 'Herbal alami untuk meningkatkan fungsi otak, memori, dan konsentrasi. Ideal untuk pelajar dan profesional.',
                'usage'         => "1. Minum 2 kapsul setelah sarapan\n2. Konsumsi rutin minimal 1 bulan\n3. Hindari konsumsi bersamaan dengan obat pengencer darah\n4. Simpan di tempat kering dan sejuk",
                'benefits'      => "• Meningkatkan daya ingat dan konsentrasi\n• Mengurangi stress dan kecemasan\n• Memperbaiki kualitas tidur\n• Mendukung kesehatan saraf",
                'composition'   => "Pegagan (Centella asiatica) 350mg, Ginkgo Biloba Ekstrak 50mg, Vitamin B Komplex",
                'price'         => 110000,
                'discount_price'=> 95000,
                'stock'         => 70,
                'is_featured'   => true,
                'is_bestseller' => false,
                'rating'        => 4.6,
                'rating_count'  => 134,
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'Daun Sirsak Anti Oksidan',
                'slug'          => 'daun-sirsak-anti-oksidan',
                'description'   => 'Ekstrak daun sirsak berkualitas tinggi yang kaya antioksidan. Membantu melawan radikal bebas dan menjaga sel tubuh tetap sehat.',
                'usage'         => "1. Minum 2 kapsul 2× sehari\n2. Sesudah makan pagi dan malam\n3. Minum air putih yang cukup\n4. Konsultasikan dengan dokter bila sedang hamil",
                'benefits'      => "• Kaya antioksidan tinggi\n• Membantu melawan sel abnormal\n• Meningkatkan sistem imun\n• Anti-inflamasi alami",
                'composition'   => "Ekstrak Daun Sirsak (Annona muricata) 500mg, Vitamin C 100mg, Zinc 10mg",
                'price'         => 75000,
                'discount_price'=> 65000,
                'stock'         => 100,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 167,
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'Herbal Sendi Flex Gel',
                'slug'          => 'herbal-sendi-flex-gel',
                'description'   => 'Gel herbal untuk dioleskan pada sendi yang nyeri. Formula canggih dengan bahan herbal pilihan untuk meredakan peradangan.',
                'usage'         => "1. Oleskan tipis pada area yang nyeri\n2. Pijat ringan selama 2 menit\n3. Gunakan 3× sehari secara teratur\n4. Cuci tangan setelah penggunaan",
                'benefits'      => "• Meredakan nyeri sendi secara cepat\n• Anti-inflamasi dan analgesik alami\n• Cocok untuk rematik dan artritis\n• Aman digunakan jangka panjang",
                'composition'   => "Jahe Merah Ekstrak 15%, Menthol 5%, Capsaicin 0.025%, Arnica Montana Ekstrak",
                'price'         => 88000,
                'discount_price'=> null,
                'stock'         => 55,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.3,
                'rating_count'  => 89,
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'Detox Ginjal Premium Tea',
                'slug'          => 'detox-ginjal-premium-tea',
                'description'   => 'Racikan teh herbal premium khusus untuk detoksifikasi ginjal dengan 7 bahan herbal pilihan terbaik Indonesia.',
                'price'         => 72000,
                'discount_price'=> 60000,
                'stock'         => 85,
                'usage'         => "1. Seduh 1 sachet dengan 250ml air panas\n2. Diamkan 10 menit\n3. Minum 3× sehari sebelum makan\n4. Dianjurkan minum air putih 2-3 liter per hari",
                'benefits'      => "• Membersihkan racun di ginjal\n• Mencegah pembentukan batu ginjal\n• Melancarkan buang air kecil\n• Menjaga tekanan darah normal",
                'composition'   => "Kumis Kucing, Tempuyung, Meniran, Akar Alang-alang, Daun Salam, Daun Alpukat, Seledri",
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.6,
                'rating_count'  => 142,
                'categories'    => ['ginjal'],
            ],
        ];

        $categoryMap = \App\Models\Category::pluck('id', 'slug')->toArray();

        foreach ($products as $data) {
            $catSlugs = $data['categories'];
            unset($data['categories']);

            $product = Product::create($data);

            $catIds = array_filter(array_map(fn($slug) => $categoryMap[$slug] ?? null, $catSlugs));
            $product->categories()->sync($catIds);
        }
    }
}
