<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductReplaceSeeder extends Seeder
{
    /**
     * Hapus semua produk lama dan isi ulang dengan 21 produk Bharata Herbal.
     * Data pelanggan, pesanan, dan kategori TIDAK terpengaruh.
     */
    public function run(): void
    {
        $this->command->info('🗑️  Menghapus semua produk lama...');

        // Nonaktifkan foreign key sementara agar truncate bisa berjalan
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys=OFF;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=0');
        }
        DB::table('product_category')->delete();
        Product::query()->delete();
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys=ON;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=1');
        }

        $this->command->info('✅ Semua produk lama telah dihapus.');
        $this->command->info('📦 Mengisi 21 produk baru Bharata Herbal...');

        // Ambil map kategori (slug => id)
        $categoryMap = Category::pluck('id', 'slug')->toArray();

        $products = [
            [
                'name'          => 'PREFILAX BHRATA',
                'slug'          => 'prefilax-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan pencernaan, mengatasi ambeien, sembelit, dan iritasi anus.',
                'composition'   => 'Graptophyllum pictum (Daun Ungu)',
                'usage'         => '3x2 kapsul sehari, 15 menit sebelum makan',
                'benefits'      => "• Mengatasi ambeien\n• Meredakan sembelit\n• Mengurangi iritasi anus\n• Menjaga kesehatan pencernaan",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => true,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/prefilax-bhrata.png',
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'TRIGANOS BHRATA',
                'slug'          => 'triganos-bhrata',
                'description'   => 'Suplemen herbal antibakteri alami untuk infeksi area genital dan saluran kemih.',
                'composition'   => 'Andrographis paniculata, Tinospora crispa',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Antibakteri alami\n• Mengatasi infeksi genital\n• Menjaga kesehatan saluran kemih\n• Meningkatkan imunitas",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/triganos-bhrata.png',
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'ORTHAFIT BHRATA',
                'slug'          => 'orthafit-bhrata',
                'description'   => 'Herbal untuk kesehatan ginjal dan saluran kemih.',
                'composition'   => 'Plantago major, Orthosiphon aristatus',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan ginjal\n• Melancarkan saluran kemih\n• Mencegah batu ginjal\n• Detoksifikasi ginjal alami",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/orthafit-bhrata.png',
                'categories'    => ['ginjal'],
            ],
            [
                'name'          => 'DEKAPRO BHRATA',
                'slug'          => 'dekapro-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan hati dan metabolisme tubuh.',
                'composition'   => 'Cyperus rotundus, Curcuma xanthorrhiza',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan hati\n• Meningkatkan metabolisme\n• Melancarkan pencernaan\n• Anti-inflamasi alami",
                'price'         => 295000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/dekapro-bhrata.png',
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'LIBAVER BHRATA',
                'slug'          => 'libaver-bhrata',
                'description'   => 'Suplemen herbal khusus untuk kesehatan hati dan meningkatkan nafsu makan.',
                'composition'   => 'Curcuma xanthorrhiza, Curcuma domestica',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan hati\n• Meningkatkan nafsu makan\n• Melancarkan pencernaan\n• Detoksifikasi liver",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/libaver-bhrata.png',
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'GALRIDA BHRATA',
                'slug'          => 'galrida-bhrata',
                'description'   => 'Suplemen herbal terapi pendamping untuk daya tahan tubuh.',
                'composition'   => 'Annona muricata, Typhonium flagelliforme',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Meningkatkan daya tahan tubuh\n• Terapi pendamping kesehatan\n• Antioksidan alami\n• Memperkuat imunitas",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => true,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/galrida-bhrata.png',
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'ETHERAL BHRATA',
                'slug'          => 'etheral-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan jantung dan sirkulasi darah.',
                'composition'   => 'Allium sativum, Guazuma ulmifolia',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan jantung\n• Melancarkan sirkulasi darah\n• Menurunkan kolesterol\n• Menjaga tekanan darah normal",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/etheral-bhrata.png',
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'ANTAPRO BHRATA',
                'slug'          => 'antapro-bhrata',
                'description'   => 'Herbal untuk memperbaiki sirkulasi darah dan pemulihan tubuh.',
                'composition'   => 'Centella asiatica (Pegagan)',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Memperbaiki sirkulasi darah\n• Mempercepat pemulihan tubuh\n• Meningkatkan fungsi otak\n• Anti-inflamasi alami",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/antapro-bhrata.png',
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'PREGNADEV SW BHRATA',
                'slug'          => 'pregnadev-sw-bhrata',
                'description'   => 'Suplemen herbal untuk program kehamilan (promil).',
                'composition'   => 'Ekstrak herbal kesuburan',
                'usage'         => '2x2 kapsul sehari',
                'benefits'      => "• Mendukung program kehamilan\n• Meningkatkan kesuburan\n• Menjaga kesehatan reproduksi\n• Nutrisi optimal untuk promil",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/pregnadev-sw-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'RETLIFA BHRATA',
                'slug'          => 'retlifa-bhrata',
                'description'   => 'Suplemen herbal untuk fungsi jantung dan metabolisme lemak.',
                'composition'   => 'Crataegus oxyacantha, Coenzyme Q10',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga fungsi jantung\n• Metabolisme lemak optimal\n• Menurunkan kolesterol\n• Antioksidan jantung",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/retlifa-bhrata.png',
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'CORDEPRO BHRATA',
                'slug'          => 'cordepro-bhrata',
                'description'   => 'Suplemen herbal multivitamin untuk daya tahan tubuh dan kesehatan organ vital.',
                'composition'   => 'Cinnamomum zeylanicum, Curcuma mangga',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Meningkatkan daya tahan tubuh\n• Multivitamin herbal alami\n• Menjaga kesehatan organ vital\n• Antioksidan kuat",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => true,
                'is_bestseller' => true,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/cordepro-bhrata.png',
                'categories'    => ['imunitas'],
            ],
            [
                'name'          => 'GERDAFOST BHRATA',
                'slug'          => 'gerdafost-bhrata',
                'description'   => 'Suplemen herbal untuk mengatasi maag dan GERD.',
                'composition'   => 'Curcuma domestica (Kunyit)',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Mengatasi maag\n• Meredakan GERD\n• Melindungi lambung\n• Anti-asam lambung alami",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/gerdafost-bhrata.png',
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'SPERAGOOD BHRATA',
                'slug'          => 'speragood-bhrata',
                'description'   => 'Herbal untuk meningkatkan kualitas dan jumlah sperma.',
                'composition'   => 'Pimpinella pruatjan, Eurycoma longifolia',
                'usage'         => '2x2 kapsul sehari',
                'benefits'      => "• Meningkatkan kualitas sperma\n• Menambah jumlah sperma\n• Mendukung kesuburan pria\n• Vitalitas reproduksi",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/speragood-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'REDAPRO BHRATA',
                'slug'          => 'redapro-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan mata dan fungsi penglihatan.',
                'composition'   => 'Vaccinium myrtillus (Bilberry)',
                'usage'         => '2x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan mata\n• Meningkatkan fungsi penglihatan\n• Antioksidan mata\n• Mencegah degenerasi makula",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/redapro-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'HEXFIDA BHRATA',
                'slug'          => 'hexfida-bhrata',
                'description'   => 'Suplemen herbal untuk gangguan lambung dan peradangan pencernaan.',
                'composition'   => 'Ekstrak kunyit',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Meredakan gangguan lambung\n• Mengurangi peradangan pencernaan\n• Melindungi dinding lambung\n• Anti-inflamasi saluran cerna",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/hexfida-bhrata.png',
                'categories'    => ['pencernaan'],
            ],
            [
                'name'          => 'FETAMAX BHRATA',
                'slug'          => 'fetamax-bhrata',
                'description'   => 'Suplemen herbal untuk menambah nafsu makan dan berat badan.',
                'composition'   => 'Curcuma xanthorrhiza, Zingiber zerumbet',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menambah nafsu makan\n• Meningkatkan berat badan\n• Memperbaiki metabolisme\n• Nutrisi optimal tubuh",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/fetamax-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'FEMMIFRESH BHRATA',
                'slug'          => 'femmifresh-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan organ kewanitaan.',
                'composition'   => 'Quercus infectoria, Piper betle',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan organ kewanitaan\n• Antibakteri alami\n• Menjaga keseimbangan flora vagina\n• Menghilangkan keputihan",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/femmifresh-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'APIREX BHRATA',
                'slug'          => 'apirex-bhrata',
                'description'   => 'Suplemen herbal untuk menjaga tekanan darah tetap stabil.',
                'composition'   => 'Apium graveolens (Seledri)',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menstabilkan tekanan darah\n• Mencegah hipertensi\n• Melancarkan sirkulasi darah\n• Menjaga kesehatan jantung",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/apirex-bhrata.png',
                'categories'    => ['persendian'],
            ],
            [
                'name'          => 'VIGAREX BHRATA',
                'slug'          => 'vigarex-bhrata',
                'description'   => 'Suplemen herbal untuk stamina dan performa pria.',
                'composition'   => 'Tribulus terrestris, Panax ginseng',
                'usage'         => '1x2 kapsul sebelum aktivitas',
                'benefits'      => "• Meningkatkan stamina pria\n• Meningkatkan performa\n• Vitalitas dan energi optimal\n• Herbal maskulinitas alami",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => true,
                'is_bestseller' => true,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/vigarex-bhrata.png',
                'categories'    => ['stamina'],
            ],
            [
                'name'          => 'VELLARE BHRATA',
                'slug'          => 'vellare-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan ginjal dan saluran empedu.',
                'composition'   => 'Strobilanthes crispus (Keji Beling)',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan ginjal\n• Membersihkan saluran empedu\n• Mencegah batu ginjal dan empedu\n• Detoksifikasi organ dalam",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/vellare-bhrata.png',
                'categories'    => ['ginjal'],
            ],
            [
                'name'          => 'VERDILLA BHRATA',
                'slug'          => 'verdilla-bhrata',
                'description'   => 'Suplemen herbal untuk kesehatan sistem pernapasan.',
                'composition'   => 'Curcuma xanthorrhiza, Selaginella doederleinii',
                'usage'         => '3x2 kapsul sehari',
                'benefits'      => "• Menjaga kesehatan pernapasan\n• Meredakan sesak napas\n• Anti-inflamasi saluran napas\n• Memperkuat paru-paru",
                'price'         => 275000,
                'discount_price'=> null,
                'stock'         => 50,
                'is_featured'   => false,
                'is_bestseller' => false,
                'rating'        => 4.5,
                'rating_count'  => 0,
                'sales_count'   => 0,
                'image'         => 'products/verdilla-bhrata.png',
                'categories'    => ['persendian'],
            ],
        ];

        foreach ($products as $index => $data) {
            $catSlugs = $data['categories'];
            unset($data['categories']);

            $product = Product::firstOrCreate(
                ['slug' => $data['slug']],
                $data
            );

            // Sinkronisasi kategori
            $catIds = array_filter(
                array_map(fn($slug) => $categoryMap[$slug] ?? null, $catSlugs)
            );
            $product->categories()->sync($catIds);

            $this->command->info("  ✅ [{$index}/{$product->name}] Berhasil disimpan.");
        }

        $this->command->info('');
        $this->command->info('🎉 Selesai! 21 produk Bharata Herbal berhasil dimasukkan ke database.');
        $this->command->info('🖼️  Gambar produk tersedia di storage/app/public/products/');
    }
}
